src/main/java/de/zulu/zuluvoting/persistence/entity/Organiser.java
package de.zulu.zuluvoting.persistence.entity;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.validation.constraints.Pattern;

@NamedQueries({
    @NamedQuery(name = Organiser.findByUsername, query = "SELECT o FROM Organiser o WHERE o.username = :username"),
    @NamedQuery(name = Organiser.findAllOrganisers, query = "SELECT o FROM Organiser o WHERE o.username != 'admin'")
})
@Entity
public class Organiser implements Serializable {

    public static final String findByUsername = "Organiser.findByUsername";
    public static final String findAllOrganisers = "Organiser.findAllOrganisers";

    @Enumerated(EnumType.STRING)
    private UserGroup userGroup;

    public UserGroup getUserGroup() {
        return userGroup;
    }

    public void setUserGroup(UserGroup userGroup) {
        this.userGroup = userGroup;
    }

    @Id
    @GeneratedValue
    private Long id;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    @Column(unique = true)
    private String username;

    private String realname;

    @Pattern(regexp = "^[_A-Za-z0-9-\\\\+]+(\\\\.[_A-Za-z0-9-]+)*@"
            + "uni-koblenz.de", message = "Invalid email address.")
    @Column(unique = true)
    private String email;
    private String password;

    @ManyToMany(mappedBy = "organisers")
    private List<Poll> polls;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getRealname() {
        return realname;
    }

    public void setRealname(String realname) {
        this.realname = realname;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public List<Poll> getPolls() {
        return polls;
    }

    public void setPolls(List<Poll> polls) {
        this.polls = polls;
    }

    @Override
    public String toString() {
        return "Organiser{"
                + "userGroup=" + userGroup
                + ", id=" + id
                + ", username='" + username + '\''
                + ", realname='" + realname + '\''
                + ", email='" + email + '\''
                + ", password='" + password + '\''
                + ", polls=" + polls
                + '}';
    }
}

src/main/java/de/zulu/zuluvoting/controller/OrganisersController.java
package de.zulu.zuluvoting.controller;

import de.zulu.zuluvoting.persistence.entity.Organiser;
import de.zulu.zuluvoting.persistence.entity.Poll;
import de.zulu.zuluvoting.services.OrganiserService;
import de.zulu.zuluvoting.services.PollService;
import de.zulu.zuluvoting.services.UserService;
import java.io.Serializable;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

@SessionScoped
@Named
public class OrganisersController implements Serializable {

    @Inject
    PollService pollService;

    @Inject
    OrganiserService organiserService;

    @Inject
    UserService userService;

    private Poll poll;

    public Poll getPoll() {
        return poll;
    }

    public void setPoll(Poll poll) {
        this.poll = poll;
    }

    public String doDeleteOrganiser(Organiser organiser) {
        if (userService.isAdministrator()) {
            organiserService.deleteOrganiser(organiser);
        } else {
            pollService.removeOrganiserFromPoll(poll, organiser);
        }
        return Pages.ORGANISER_LIST;
    }

    public List<Organiser> getAllOrganisers() {
        return organiserService.getAllOrgnanisers();
    }
}

src/main/java/de/zulu/zuluvoting/controller/PollListController.java
package de.zulu.zuluvoting.controller;

import de.zulu.zuluvoting.persistence.entity.Poll;
import de.zulu.zuluvoting.services.PollService;
import de.zulu.zuluvoting.services.UserService;
import java.io.Serializable;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

@SessionScoped
@Named
public class PollListController implements Serializable {

    @Inject
    OrganisersController organisersController;
    @Inject
    ParticipantListController participantListController;
    @Inject
    PollEditController pollEditController;

    @Inject
    PollService pollService;

    @Inject
    UserService userService;

    public List<Poll> viewAllPolls() {
        return pollService.getAllPolls();
    }

    public List<Poll> getPollsOwnedByOrganiser() {
        return pollService.getAllPollsOwnedByCurrentUser();
    }

    public String doViewParticipantList(Poll poll) {
        participantListController.setPoll(poll);
        participantListController.setMode(ParticipantListController.Mode.READONLY);
        return Pages.PARTICIPANT_LIST;
    }

    public String doViewOrganiserList(Poll poll) {
        organisersController.setPoll(poll);
        return Pages.ORGANISER_LIST;
    }

    public String doDeletePoll(Poll poll) {
        pollService.deletePoll(poll);
        return Pages.POLL_LIST;
    }

    public String doAddPoll() {
        pollEditController.setPollToEdit(PollEditController.Mode.ADD);
        return Pages.POLL_EDIT;
    }

    public String doEditPoll(Poll poll) {
        pollEditController.setPollToEdit(PollEditController.Mode.EDIT, poll);
        return Pages.POLL_EDIT;
    }

    public String getResultURL(Poll poll) {
        return "https://localhost:8181/zuluvoting/results?id=" + poll.getId();
    }

    public String getFormattedState(Poll poll) {
        String result = poll.getState().toString().substring(0, 1).toUpperCase() + poll.getState().toString().substring(1).toLowerCase();
        return result;
    }

    public String formatStart(Poll poll) {
        long now = System.currentTimeMillis();
        long start = poll.getStart().getTime();
        String formatted = formatPeriod(start, now);
        switch (poll.getState()) {
            case PREPARED:
                if (now < start) {
                    return "(In " + formatted + ")";
                } else {
                    return "(" + formatted + " ago)";
                }
            case STARTED:
                return "In " + formatted;
            case RUNNING:
                return formatted + " ago";
            case FINISHED:
                return formatted + " ago";
        }
        return null;
    }

    public String formatEnd(Poll poll) {
        long now = System.currentTimeMillis();
        long end = poll.getEnd().getTime();
        String formatted = formatPeriod(now, end);
        switch (poll.getState()) {
            case PREPARED:
                if (now < end) {
                    return "(In " + formatted + ")";
                } else {
                    return "(" + formatted + " ago)";
                }
            case STARTED:
                return "In " + formatted;
            case RUNNING:
                return "In " + formatted;
            case FINISHED:
                return formatted + " ago";
        }
        return null;
    }

    private static final long SECOND = 1000;
    private static final long MINUTE = SECOND * 60;
    private static final long HOUR = MINUTE * 60;
    private static final long DAY = HOUR * 24;

    private static String formatPeriod(long start, long end) {
        long diff = Math.abs(end - start);
        String formatted;
        if (diff < MINUTE) {
            long seconds = (diff / SECOND);
            formatted = seconds + " " + (seconds == 1 ? "second" : "seconds");
        } else if (diff < HOUR) {
            long minutes = (diff / MINUTE);
            formatted = minutes + " " + (minutes == 1 ? "minute" : "minutes");
        } else if (diff < DAY) {
            long hours = (diff / HOUR);
            formatted = hours + " " + (hours == 1 ? "hour" : "hours");
        } else {
            long days = (diff / DAY);
            formatted = days + " " + (days == 1 ? "day" : "days");
        }
        return "~" + formatted;
    }

    public String getVotesMessage(Poll poll) {
        if (poll.isParticipationTracking()) {
            return poll.getVoteCount() + "/" + poll.getParticipants().size();
        } else {
            return "?/" + poll.getParticipants().size();
        }
    }
}

src/main/java/de/zulu/zuluvoting/controller/TakePollController.java
package de.zulu.zuluvoting.controller;

import de.zulu.zuluvoting.persistence.entity.Item;
import de.zulu.zuluvoting.persistence.entity.Option;
import de.zulu.zuluvoting.persistence.entity.Participant;
import de.zulu.zuluvoting.persistence.entity.Poll;
import de.zulu.zuluvoting.persistence.entity.Token;
import de.zulu.zuluvoting.services.ParticipantService;
import de.zulu.zuluvoting.services.PollService;
import de.zulu.zuluvoting.services.TokenService;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ejb.EJBException;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.model.SelectItem;
import javax.inject.Inject;
import org.primefaces.context.RequestContext;

@ViewScoped
@ManagedBean
public class TakePollController implements Serializable {

    @Inject
    private PollService pollService;
    @Inject
    private TokenService tokenService;
    @Inject
    private ParticipantService participantService;
    private String rawToken;
    private Token token;
    private Poll poll;
    private final Map<Long, Option> selectedRadioOptions = new HashMap<>(); // ItemId -> Option[]
    private final Map<Long, List<SelectItem>> availableItemsWithOptions = new HashMap<>(); // ItemId -> SelectItem[]

    public Map<Long, Option> getSelectedRadioOptions() {
        return selectedRadioOptions;
    }

    public Map<Long, List<SelectItem>> getAvailableItemsWithOptions() {
        return availableItemsWithOptions;
    }

    public Token getToken() {
        return token;
    }

    public void setToken(Token token) {
        this.token = token;
    }

    public String getRawToken() {
        return rawToken;
    }

    public Poll getPoll() {
        return poll;
    }

    public void setRawToken(String rawToken) {
        this.rawToken = rawToken;
        try {
            this.token = tokenService.findTokenByValue(this.rawToken);
        } catch (EJBException e) {
            this.token = null;
        }
        if (token != null) {
            this.poll = token.getPoll();
            for (Item item : poll.getItems()) {
                List<SelectItem> optionsList = new ArrayList<>();
                for (int i = 0; i < item.getOptions().size(); i++) {
                    Option option = item.getOptions().get(i);
                    String description = "";
                    if (option.getDescription() != null && !option.getDescription().equals("")) {
                        description = "\t// " + option.getDescription();
                    }
                    optionsList.add(new SelectItem(
                            option,
                            "<b>" + option.getShortName() + "</b>"
                            + description,
                            option.getDescription(),
                            false,
                            false
                    )
                    );
                }
                selectedRadioOptions.put(item.getId(), item.getOptions().get(0));
                availableItemsWithOptions.put(item.getId(), optionsList);
            }
        }
        RequestContext.getCurrentInstance().update("pollForm");
        RequestContext.getCurrentInstance().update("tokenForm");
    }

    public Item getItemFromListById(Long id) {
        for (Item item : poll.getItems()) {
            if (item.getId().equals(id)) {
                return item;
            }
        }
        return null;
    }

    public List<Long> getItemIds() {
        return new ArrayList<>(availableItemsWithOptions.keySet());
    }

    public List<SelectItem> getSelectItemsByItemId(Long itemId) {
        return availableItemsWithOptions.get(itemId);
    }

    public String submit() {
        if (token.isValid()) {
            for (Long itemId : selectedRadioOptions.keySet()) {
                Option selectedOption = selectedRadioOptions.get(itemId);
                if (selectedOption == null) {
                    continue;
                }
                for (Item item : poll.getItems()) {
                    if (itemId.equals(item.getId())) {
                        for (Option option : item.getOptions()) {
                            if (option.getId().equals(selectedOption.getId())) {
                                option.setCount(option.getCount() + 1);
                            }
                        }
                    }
                }
            }

            poll.setVoteCount(poll.getVoteCount() + 1);
            pollService.updatePoll(poll);
            token.setValid(false);
            Participant participant = this.token.getParticipant();
            participant.setHasVoted(true);
            participantService.updateParticipant(participant);
            tokenService.updateToken(token);
            this.token = null;
            this.rawToken = null;
            this.poll = null;
            return Pages.VOTED;
        } else {
            RequestContext.getCurrentInstance().update("pollForm");
            RequestContext.getCurrentInstance().update("tokenForm");
            return null;
        }
    }
}

src/main/java/de/zulu/zuluvoting/services/UserServiceBean.java
package de.zulu.zuluvoting.services;

import de.zulu.zuluvoting.persistence.entity.Organiser;
import java.io.IOException;
import java.io.Serializable;
import java.security.Principal;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.TypedQuery;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@SessionScoped
@Named
public class UserServiceBean implements Serializable, UserService {

    @PersistenceContext
    private EntityManager entityManager;

    private Organiser organiser;

    @Override
    public Organiser getOrganiser() {
        if (organiser == null) {
            ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
            Principal principal = ec.getUserPrincipal();
            if (principal != null) {
                getOrganiserFromDb(principal.getName());
            }

        }
        return organiser;
    }

    private void getOrganiserFromDb(String username) {
        TypedQuery<Organiser> query = entityManager.createNamedQuery(Organiser.findByUsername, Organiser.class);
        query.setParameter("username", username);
        Organiser o = query.getSingleResult();
        if (o == null) {
            organiser = null;
        }
        organiser = o;
    }

    @Override
    public void logout() {
        HttpServletRequest req = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
        try {
            HttpServletResponse res = (HttpServletResponse) FacesContext.getCurrentInstance().getExternalContext().getResponse();
            res.sendRedirect(req.getContextPath());
        } catch (IOException ex) {
            System.err.println("Error at logout!");
        } finally {
            organiser = null;
            FacesContext.getCurrentInstance().responseComplete();
            req.getSession(false).invalidate();
        }
    }

    @Override
    public boolean isAdministrator() {
        return FacesContext.getCurrentInstance().getExternalContext().isUserInRole("ADMIN");
    }
}

src/main/webapp/secured/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      lang="en">
    <h:body>
        <ui:composition template="../WEB-INF/templates/securedTemplate.xhtml">
            <ui:define name="title">Zuluvoting | Home</ui:define>
            <ui:define name="content">
                 <div class="jumbotron">
                    <div class="container">
                        <h1>
                            <img src="../resources/img/zulu.png" width="300" height="225" alt="Zuluvoting"/>
                            Zuluvoting
                        </h1>
                    </div>
                </div>
                <div class="container">
                    <h1>Hello <b>#{userServiceBean.organiser.realname}(#{userServiceBean.organiser.email}),</b><br/>
                        Welcome to Zuluvoting</h1>
                    Click <a href="http://localhost:8080/zuluvoting/secured/pollList">here</a>, to get to your polls.
                </div>
            </ui:define>     
        </ui:composition>
    </h:body>
</html>

src/main/webapp/secured/organisers.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      lang="en">
    <ui:composition template="../WEB-INF/templates/securedTemplate.xhtml">
        <ui:define name="title">Organisers</ui:define>
        <ui:define name="content">
            <div class="container">
                <h2>Organisers</h2>
                <h:form>
                    <p:messages globalOnly="true" />
                    <h:dataTable value="#{organisersController.poll.organisers}"
                                 var="organiser"
                                 styleClass="table table-striped table-bordered">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Username" />
                            </f:facet>
                            <h:outputText value="#{organiser.username}" />
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Real Name" />
                            </f:facet>
                            <h:outputText value="#{organiser.realname}" />
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="E-Mail" />
                            </f:facet>
                            <h:outputText value="#{organiser.email}" />
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Polls" />
                            </f:facet>
                            <h:outputText value="#{organiser.polls.size()}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Actions" />
                            </f:facet>
                            <div class="btn-group btn-group-xs">
                                <ui:fragment rendered="#{userServiceBean.administrator == true}"><button type="button" class="btn btn-warning"><span class="glyphicon glyphicon-asterisk"></span></button></ui:fragment>
                                <p:commandLink 
                                    actionListener="#{organisersController.doDeleteOrganiser(organiser)}"
                                    styleClass="btn btn-danger"
                                    update="@form">
                                    <i class="glyphicon glyphicon-remove"></i>
                                    <p:confirm header="Confirmation" message="Are you sure?" icon="ui-icon-alert" />
                                </p:commandLink>       
                                <p:confirmDialog global="true">
                                    <p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes"/>
                                    <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no"/>
                                </p:confirmDialog>
                            </div>
                        </h:column>
                    </h:dataTable>
                </h:form>
                <h:form>
                        <div class="pull-right">
                            <button type="button" class="btn btn-success" onclick="window.history.back()">Continue</button>
                        </div>
               </h:form>
            </div>
        </ui:define>
    </ui:composition>
</html>

src/main/webapp/secured/pollList.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      lang="en">
    <h:body>
        <ui:composition template="../WEB-INF/templates/securedTemplate.xhtml">
            <ui:define name="title">Polls</ui:define>
            <ui:define name="content">
                <div class="container">
                    <h1>Polls</h1>
                    <h:form acceptcharset="utf-8">
                        <h:dataTable value="#{pollListController.pollsOwnedByOrganiser}" 
                                     var="poll" 
                                     styleClass="table table-striped table-bordered"
                                     columnClasses="null,null,no-wrap,no-wrap,no-wrap,pollist-actions">
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Name"/>
                                </f:facet>
                                <h:outputText value="#{poll.title}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Description"/>
                                </f:facet>
                                <h:outputText value="#{poll.description}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Status"/>
                                </f:facet>
                                <h:panelGroup class="glyphicon glyphicon-stop" rendered="#{poll.state == 'PREPARED'}"/>
                                <h:panelGroup class="glyphicon glyphicon-pause" rendered="#{poll.state == 'STARTED'}"/>
                                <h:panelGroup class="glyphicon glyphicon-play" rendered="#{poll.state == 'RUNNING'}"/>
                                <h:panelGroup class="glyphicon glyphicon-ok" rendered="#{poll.state == 'FINISHED'}"/>
                                &nbsp;
                                <i><h:outputText value="#{pollListController.getFormattedState(poll)}"/></i>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Votes"/>
                                </f:facet>
                                <h:outputText value="#{pollListController.getVotesMessage(poll)}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Start"/>
                                </f:facet>
                                <h:outputText value="#{pollListController.formatStart(poll)}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="End"/>
                                </f:facet>
                                <h:outputText value="#{pollListController.formatEnd(poll)}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Actions"/>
                                </f:facet>
                                <div class="btn-group btn-group-xs">
                                    <h:commandLink
                                        rendered="#{poll.pollState!='FINISHED'}"
                                        action="#{pollListController.doEditPoll(poll)}"
                                        styleClass="btn btn-default">
                                        <f:passThroughAttribute name="data-toggle" value="tooltip"/>
                                        <f:passThroughAttribute name="data-placement" value="top"/>
                                        <f:passThroughAttribute name="title" value="Edit poll"/>
                                        <span class="glyphicon glyphicon-pencil"/>
                                    </h:commandLink>
                                    <ui:fragment rendered="#{poll.pollState=='FINISHED'}">
                                        <a title="View Results" class="btn btn-default" href="#{pollListController.getResultURL(poll)}">
                                            <span class="glyphicon glyphicon-ok"/>
                                        </a>
                                    </ui:fragment>
                                    <h:commandLink 
                                        action="#{pollListController.doViewParticipantList(poll)}"
                                        styleClass="btn btn-default">
                                        <f:passThroughAttribute name="data-toggle" value="tooltip"/>
                                        <f:passThroughAttribute name="data-placement" value="top"/>
                                        <f:passThroughAttribute name="title" value="Show participants"/>
                                        <span class="glyphicon glyphicon-user"/>
                                    </h:commandLink>
                                    <h:commandLink 
                                        action="#{pollListController.doViewOrganiserList(poll)}"
                                        styleClass="btn btn-default">
                                        <f:passThroughAttribute name="data-toggle" value="tooltip"/>
                                        <f:passThroughAttribute name="data-placement" value="top"/>
                                        <f:passThroughAttribute name="title" value="Edit organisers"/>
                                        <span class="glyphicon glyphicon-star"/>
                                    </h:commandLink>


                                    <p:commandLink 
                                        actionListener="#{pollListController.doDeletePoll(poll)}"
                                        styleClass="btn btn-danger"
                                        update="@form">
                                        <i class="glyphicon glyphicon-remove"></i>
                                        <p:confirm header="Confirmation" message="Are you sure?" icon="ui-icon-alert" />
                                        <f:passThroughAttribute name="data-toggle" value="tooltip"/>
                                        <f:passThroughAttribute name="data-placement" value="top"/>
                                        <f:passThroughAttribute name="title" value="Delete poll"/>
                                    </p:commandLink>       
                                    <p:confirmDialog global="true">
                                        <p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes"/>
                                        <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no"/>
                                    </p:confirmDialog>

                                </div>
                            </h:column>
                        </h:dataTable>
                        <h:commandLink
                            action="#{pollListController.doAddPoll()}"
                            styleClass="btn btn-success">
                            <span class="glyphicon glyphicon-plus"/>
                            Create new Poll
                        </h:commandLink>
                    </h:form>
                </div>
            </ui:define>     
        </ui:composition>
    </h:body>
</html>


src/main/webapp/secured/test.xhtml
<html>
    <h1>Now you can call yourself a real HACKER!</h1>
<img src="http://sagelighteditor.com/galleries/albums/test-album-1/smiling-new-big.jpg"/>
</html>