src/main/java/de/zulu/zuluvoting/persistence/entity/ItemType.java
package de.zulu.zuluvoting.persistence.entity;

public enum ItemType {
    /**
     * The participant may only choose between yes and no.
     */
    YES_NO,
    /**
     * The participant may choose exactly one on n options.
     */
    ONE_OF_N,
    /**
     * The participant may choose an arbitrary number of options.
     */
    M_OF_N
}

src/main/java/de/zulu/zuluvoting/persistence/entity/UserGroup.java
package de.zulu.zuluvoting.persistence.entity;

public enum UserGroup {
    USER,
    ADMIN;
}

src/main/java/de/zulu/zuluvoting/controller/CreateUserController.java
package de.zulu.zuluvoting.controller;

import de.zulu.zuluvoting.persistence.entity.Organiser;
import de.zulu.zuluvoting.persistence.entity.UserGroup;
import de.zulu.zuluvoting.services.OrganiserService;
import de.zulu.zuluvoting.utils.PasswordEncoder;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

@SessionScoped
@Named
public class CreateUserController implements Serializable {

    @Inject
    OrganiserService organiserService;

    private String password;

    private Organiser organiser = new Organiser();

    public Organiser getOrganiser() {
        return organiser;
    }

    public void setOrganiser(Organiser organiser) {
        this.organiser = organiser;
    }

    public String createUser() {
        organiser.setPassword(PasswordEncoder.encodePassword(password));
        organiser.setUserGroup(UserGroup.USER);
        try {
            organiserService.createOrganiser(organiser);
        } catch (Exception e) {
            FacesMessage facesMessage = new FacesMessage(
                    FacesMessage.SEVERITY_ERROR, "User already exists!", null);
            FacesContext.getCurrentInstance().addMessage(null, facesMessage);
            organiser = new Organiser();
            password = null;
            return Pages.CREATE_USER;
        }
        FacesMessage facesMessage = new FacesMessage(
                FacesMessage.SEVERITY_INFO, "New user succesfully created!", null);
        FacesContext.getCurrentInstance().addMessage(null, facesMessage);
        organiser = new Organiser();
        password = null;
        return Pages.CREATE_USER;

    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPassword() {
        return password;
    }
}

src/main/java/de/zulu/zuluvoting/controller/OrganisersController.java
package de.zulu.zuluvoting.controller;

import de.zulu.zuluvoting.persistence.entity.Organiser;
import de.zulu.zuluvoting.persistence.entity.Poll;
import de.zulu.zuluvoting.services.OrganiserService;
import de.zulu.zuluvoting.services.PollService;
import de.zulu.zuluvoting.services.UserService;
import java.io.Serializable;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

@SessionScoped
@Named
public class OrganisersController implements Serializable {

    @Inject
    PollService pollService;

    @Inject
    OrganiserService organiserService;

    @Inject
    UserService userService;

    private Poll poll;

    public Poll getPoll() {
        return poll;
    }

    public void setPoll(Poll poll) {
        this.poll = poll;
    }

    public String doDeleteOrganiser(Organiser organiser) {
        if (userService.isAdministrator()) {
            organiserService.deleteOrganiser(organiser);
        } else {
            pollService.removeOrganiserFromPoll(poll, organiser);
        }
        return Pages.ORGANISER_LIST;
    }

    public List<Organiser> getAllOrganisers() {
        return organiserService.getAllOrgnanisers();
    }
}

src/main/java/de/zulu/zuluvoting/controller/ParticipantListController.java
package de.zulu.zuluvoting.controller;

import de.zulu.zuluvoting.persistence.entity.Participant;
import de.zulu.zuluvoting.persistence.entity.Poll;
import de.zulu.zuluvoting.persistence.entity.Token;
import de.zulu.zuluvoting.services.PollService;
import java.io.Serializable;
import java.util.UUID;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

@SessionScoped
@Named
public class ParticipantListController implements Serializable {

    public enum Mode {
        EDIT,
        READONLY
    }

    private Mode mode;

    public Mode getMode() {
        return mode;
    }

    public void setMode(Mode mode) {
        this.mode = mode;
    }

    @Inject
    PollService pollService;

    private Poll poll;

    private String newEmail;

    public String getNewEmail() {
        return newEmail;
    }

    public void setNewEmail(String newEmail) {
        this.newEmail = newEmail;
    }

    public String doDeleteParticipant(Participant participant) {
        pollService.removeParticipantFromPoll(poll, participant);

        removeCorrespondingToken(participant);

        return Pages.PARTICIPANT_LIST;
    }

    public String doAddParticipant() {
        Participant participant = new Participant();
        participant.setEmail(newEmail);
        participant.setHasVoted(false);
        newEmail = null;

        if (poll.getParticipants().contains(participant)) {
            FacesMessage facesMessage = new FacesMessage(
                    FacesMessage.SEVERITY_ERROR, "Participants have to be unique.", null);
            FacesContext.getCurrentInstance().addMessage(null, facesMessage);
            return Pages.PARTICIPANT_LIST;
        }
        poll.getParticipants().add(participant);

        createToken(participant);

        return Pages.PARTICIPANT_LIST;
    }

    public Poll getPoll() {
        return poll;
    }

    public void setPoll(Poll poll) {
        this.poll = poll;
    }

    public String doContinue() {
        if (poll.getParticipants().size() < 3) {
            FacesMessage facesMessage = new FacesMessage(
                    FacesMessage.SEVERITY_ERROR, "You have to specify at least 3 participants!", null);
            FacesContext.getCurrentInstance().addMessage(null, facesMessage);
            return Pages.PARTICIPANT_LIST;
        }
        poll = null;
        mode = null;
        return Pages.POLL_EDIT;
    }

    private void createToken(Participant p) {
        Token token = new Token();
        token.setParticipant(p);
        token.setPoll(poll);
        token.setValue(UUID.randomUUID().toString());
        poll.getTokens().add(token);
    }

    private void removeCorrespondingToken(Participant p) {
        Token tokenToRemove = null;
        for (Token t : poll.getTokens()) {
            if (t.getParticipant().equals(p)) {
                tokenToRemove = t;
                break;
            }
        }
        poll.getTokens().remove(tokenToRemove);
    }
}

src/main/java/de/zulu/zuluvoting/controller/PollListController.java
package de.zulu.zuluvoting.controller;

import de.zulu.zuluvoting.persistence.entity.Poll;
import de.zulu.zuluvoting.services.PollService;
import de.zulu.zuluvoting.services.UserService;
import java.io.Serializable;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

@SessionScoped
@Named
public class PollListController implements Serializable {

    @Inject
    OrganisersController organisersController;
    @Inject
    ParticipantListController participantListController;
    @Inject
    PollEditController pollEditController;

    @Inject
    PollService pollService;

    @Inject
    UserService userService;

    public List<Poll> viewAllPolls() {
        return pollService.getAllPolls();
    }

    public List<Poll> getPollsOwnedByOrganiser() {
        return pollService.getAllPollsOwnedByCurrentUser();
    }

    public String doViewParticipantList(Poll poll) {
        participantListController.setPoll(poll);
        participantListController.setMode(ParticipantListController.Mode.READONLY);
        return Pages.PARTICIPANT_LIST;
    }

    public String doViewOrganiserList(Poll poll) {
        organisersController.setPoll(poll);
        return Pages.ORGANISER_LIST;
    }

    public String doDeletePoll(Poll poll) {
        pollService.deletePoll(poll);
        return Pages.POLL_LIST;
    }

    public String doAddPoll() {
        pollEditController.setPollToEdit(PollEditController.Mode.ADD);
        return Pages.POLL_EDIT;
    }

    public String doEditPoll(Poll poll) {
        pollEditController.setPollToEdit(PollEditController.Mode.EDIT, poll);
        return Pages.POLL_EDIT;
    }

    public String getResultURL(Poll poll) {
        return "https://localhost:8181/zuluvoting/results?id=" + poll.getId();
    }

    public String getFormattedState(Poll poll) {
        String result = poll.getState().toString().substring(0, 1).toUpperCase() + poll.getState().toString().substring(1).toLowerCase();
        return result;
    }

    public String formatStart(Poll poll) {
        long now = System.currentTimeMillis();
        long start = poll.getStart().getTime();
        String formatted = formatPeriod(start, now);
        switch (poll.getState()) {
            case PREPARED:
                if (now < start) {
                    return "(In " + formatted + ")";
                } else {
                    return "(" + formatted + " ago)";
                }
            case STARTED:
                return "In " + formatted;
            case RUNNING:
                return formatted + " ago";
            case FINISHED:
                return formatted + " ago";
        }
        return null;
    }

    public String formatEnd(Poll poll) {
        long now = System.currentTimeMillis();
        long end = poll.getEnd().getTime();
        String formatted = formatPeriod(now, end);
        switch (poll.getState()) {
            case PREPARED:
                if (now < end) {
                    return "(In " + formatted + ")";
                } else {
                    return "(" + formatted + " ago)";
                }
            case STARTED:
                return "In " + formatted;
            case RUNNING:
                return "In " + formatted;
            case FINISHED:
                return formatted + " ago";
        }
        return null;
    }

    private static final long SECOND = 1000;
    private static final long MINUTE = SECOND * 60;
    private static final long HOUR = MINUTE * 60;
    private static final long DAY = HOUR * 24;

    private static String formatPeriod(long start, long end) {
        long diff = Math.abs(end - start);
        String formatted;
        if (diff < MINUTE) {
            long seconds = (diff / SECOND);
            formatted = seconds + " " + (seconds == 1 ? "second" : "seconds");
        } else if (diff < HOUR) {
            long minutes = (diff / MINUTE);
            formatted = minutes + " " + (minutes == 1 ? "minute" : "minutes");
        } else if (diff < DAY) {
            long hours = (diff / HOUR);
            formatted = hours + " " + (hours == 1 ? "hour" : "hours");
        } else {
            long days = (diff / DAY);
            formatted = days + " " + (days == 1 ? "day" : "days");
        }
        return "~" + formatted;
    }

    public String getVotesMessage(Poll poll) {
        if (poll.isParticipationTracking()) {
            return poll.getVoteCount() + "/" + poll.getParticipants().size();
        } else {
            return "?/" + poll.getParticipants().size();
        }
    }
}

src/main/java/de/zulu/zuluvoting/controller/PollPreviewController.java
package de.zulu.zuluvoting.controller;

import de.zulu.zuluvoting.persistence.entity.Item;
import de.zulu.zuluvoting.persistence.entity.Option;
import de.zulu.zuluvoting.persistence.entity.Poll;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.enterprise.context.RequestScoped;
import javax.faces.model.SelectItem;
import javax.inject.Named;
import org.primefaces.context.RequestContext;

@RequestScoped
@Named
public class PollPreviewController implements Serializable {

    private Poll poll;
    private final Map<Long, Option> selectedRadioOptions = new HashMap<>(); // ItemId -> Option[]
    private final Map<Long, List<SelectItem>> availableItemsWithOptions = new HashMap<>(); // ItemId -> SelectItem[]

    private final Map<Long, Item> temporaryItemMap = new HashMap<>();

    public Map<Long, Option> getSelectedRadioOptions() {
        return selectedRadioOptions;
    }

    public Map<Long, List<SelectItem>> getAvailableItemsWithOptions() {
        return availableItemsWithOptions;
    }

    public void setPoll(Poll p) {
        poll = p;
        init();
    }

    public Poll getPoll() {
        return poll;
    }

    public void init() {
        long tempId = 0;
        for (Item item : poll.getItems()) {
            List<SelectItem> optionsList = new ArrayList<>();
            for (int i = 0; i < item.getOptions().size(); i++) {
                Option option = item.getOptions().get(i);
                String description = "";
                if (option.getDescription() != null && !option.getDescription().equals("")) {
                    description = "\t// " + option.getDescription();
                }
                optionsList.add(new SelectItem(
                        option,
                        "<b>" + option.getShortName() + "</b>"
                        + description,
                        option.getDescription(),
                        false,
                        false
                )
                );
            }

            temporaryItemMap.put(tempId, item);
            selectedRadioOptions.put(tempId, item.getOptions().get(0));
            availableItemsWithOptions.put(tempId, optionsList);
            tempId++;
        }

        RequestContext.getCurrentInstance().update("pollForm");
    }

    public Item getItemFromListById(Long id) {

        return temporaryItemMap.get(id);
    }

    public List<Long> getItemIds() {
        return new ArrayList<>(availableItemsWithOptions.keySet());
    }

    public List<SelectItem> getSelectItemsByItemId(Long itemId) {
        return availableItemsWithOptions.get(itemId);
    }
    
    public String doContinue(){
        return Pages.POLL_EDIT;
    }

}

src/main/java/de/zulu/zuluvoting/controller/ResultController.java
package de.zulu.zuluvoting.controller;

import de.zulu.zuluvoting.persistence.entity.Item;
import de.zulu.zuluvoting.persistence.entity.Option;
import de.zulu.zuluvoting.persistence.entity.Poll;
import de.zulu.zuluvoting.persistence.entity.PollState;
import de.zulu.zuluvoting.services.PollService;
import java.io.Serializable;
import java.util.ArrayList;
import javax.enterprise.context.RequestScoped;
import javax.faces.bean.ManagedBean;
import javax.inject.Inject;
import org.primefaces.model.chart.PieChartModel;

@RequestScoped
@ManagedBean
public class ResultController implements Serializable {

    @Inject
    PollService pollService;

    private Poll poll;
    private long pollid;
    private State state;
    private ArrayList<PieChartModel> pies;

    public ArrayList<PieChartModel> getPies() {
        return pies;
    }

    public void setPies(ArrayList<PieChartModel> pies) {
        this.pies = pies;
    }

    public enum State {

        RESULTS,
        LOWPARTICIPANTS,
        NOTFINISHED
    };

    public long getPollid() {
        return pollid;
    }

    public void setPollid(long pollid) {
        setPoll(pollService.findPollById(pollid));
        this.pollid = pollid;
    }

    public Poll getPoll() {
        return poll;
    }

    public void setPoll(Poll poll) {

        if (poll.getState() == PollState.FINISHED) {
            if (poll.getVoteCount() < 3) {
                state = State.LOWPARTICIPANTS;
            } else {
                state = State.RESULTS;
            }
        } else {
            state = State.NOTFINISHED;
        }
        this.poll = poll;
        pies = new ArrayList<>();
        createPies(poll);
    }

    public State getState() {
        return state;
    }

    public void setState(State state) {
        this.state = state;
    }

    public void createPies(Poll poll) {
        for (Item i : poll.getItems()) {
            pies.add(createPieForItem(i));
        }
    }

    public PieChartModel createPieForItem(Item item) {
        PieChartModel pie = new PieChartModel();

        for (Option o : item.getOptions()) {
            pie.set(o.getShortName(), o.getCount());
        }
        pie.setLegendPosition("w");
        pie.setShowDataLabels(true);
        return pie;
    }

    public String doCreateParticipationString() {
        return poll.getVoteCount() + " of " + poll.getParticipants().size() + " participants have voted.";
    }

    public String percent(Option option) {
        if (option.getCount() > 0) {
            return (((float) option.getCount() * 100) / ((float) poll.getVoteCount())) + "%";
        } else {
            return "0.0%";
        }
    }
}

src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet"></link>
        <script src="//code.jquery.com/jquery-2.1.1.min.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
     
        <title>Zuluvoting | Login</title>
    </head>
    
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Zulu Voting</a>
                </div>
                
                <!--
                
                <div class="navbar-collapse collapse">
                    <form class="navbar-form navbar-right" role="form">
                        <div class="form-group">
                            <input type="text" placeholder="Email" class="form-control"/>
                        </div>
                        <div class="form-group">
                            <input type="password" placeholder="Password" class="form-control"/>
                        </div>
                        <button type="submit" class="btn btn-success">Sign in</button>
                    </form>
                </div>
                -->
            </div>
                
        </div>

        <div class="jumbotron">
            <div class="container">
                <h1>
                    <img src="resources/img/zulu.png" width="300" height="225" alt="Zuluvoting"/>
                    Zuluvoting
                </h1>
            </div>
        </div>
        <div class="container">
            <h1>Welcome to Zuluvoting</h1>
            <p class="lead">Log in if you are a <a href="http://localhost:8080/zuluvoting/secured/index">organiser</a> or <a href="http://localhost:8080/zuluvoting/admin/index">administrator</a>.<br/>
                Or create <a href="http://localhost:8080/zuluvoting/users/createUser">new organiser account</a>.<br/>
                If you are a participant, go to the <a href="takePoll">poll-participation-page</a> and enter your token, or click on the link in your ivitation e-mail.</p>
        </div>
    </body>

</html>

src/main/webapp/results.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      lang="en">
    <h:head>

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet"/>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <h:outputStylesheet name="css/template.css" />

        <title>
            <h:outputText value="#{resultController.poll.title} Results"/>
        </title>
    </h:head>

    <h:body>
        <f:metadata>
            <f:viewParam id="id"
                         name="id"
                         value="#{resultController.pollid}">
            </f:viewParam>
        </f:metadata>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Zulu Voting</a>
                </div>

            </div>
        </div>
        <h:form  rendered="#{resultController.state=='LOWPARTICIPANTS'}" id="lowparticipants">
            <h1>
            Sorry, but the poll had too few participants.
            </h1>
        </h:form>
        
        <h:form  rendered="#{resultController.state=='NOTFINISHED'}" id="notfinished">
        <h1>
            Sorry, but the poll you're requesting isn't finished yet.
        </h1>
        </h:form>
        
        <h:form  rendered="#{resultController.state=='RESULTS'}" id="results">
            <div class="container">
                <h1>
                    <h:outputText value="#{resultController.poll.title}"/>
                </h1>
                <h:outputText value="#{resultController.doCreateParticipationString()}"/>
                <br/>
                <div class="container-fluid">
                    <ui:repeat id="itemList" 
                               value="#{resultController.poll.items}" 
                               var="item">
                        
                        <div class="row">
                            <hr/>
                            <div class="col-xs-12">
                                <h:outputLabel value="#{item.title}"/>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-8">
                                <div class="container-fluid">
                                    <h:dataTable value="#{item.options}"
                                                 var="option"
                                                 styleClass="table table-striped">
                                        <h:column>
                                            <f:facet name="header">Name</f:facet>
                                            <h:outputText value="#{option.shortName}"/>
                                        </h:column>
                                        <h:column>
                                            <f:facet name="header">Description</f:facet>
                                            <h:outputText value="#{option.description}"/>
                                        </h:column>
                                        <h:column>
                                            <f:facet name="header">Votes</f:facet>
                                            <h:outputText value="#{option.count}"/>
                                        </h:column>
                                        <h:column>
                                            <f:facet name="header">Percent</f:facet>
                                            <h:outputText value="#{resultController.percent(option)}"/>
                                        </h:column>
                                    </h:dataTable>
                                </div>
                                
                            </div>
                            <div class="col-xs-4">
                                <p:chart type="pie"
                                         model="#{resultController.pies.get(resultController.poll.items.indexOf(item))}"
                                         style="width: 300px; height: 200px;"/>
                            </div>
                            
                        </div>
                        
                    </ui:repeat>    
                </div>
            </div>
        </h:form>

    </h:body>
</html>


src/main/webapp/takePoll.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="WEB-INF/templates/template.xhtml">
        <ui:define name="title">

        </ui:define>
        <f:metadata>
            <f:viewParam id="token"
                         name="token"
                         value="#{takePollController.rawToken}">
            </f:viewParam>
        </f:metadata>
        <ui:define name="content">

            <!-- ======= Token valid ======= -->
            <h:panelGroup id="pollForm"
                          styleClass="container-fluid" 
                          layout="block"
                          style="margin-bottom: 12px"
                          rendered="#{takePollController.token != null and takePollController.token.valid}">
                <div class="row">
                    <div class="col-md-4 col-md-offset-4">
                        <h1 class="page-header"><h:outputText value="#{takePollController.poll.title}"/></h1>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 col-md-offset-4">
                        <p><h:outputText value="#{takePollController.poll.description}"/></p>
                    </div>
                </div>
                <h:form>
                    <ui:repeat value="#{takePollController.itemIds}"
                               var="id">

                        <div class="row">
                            <br/>
                        </div>
                        <div class="row">
                            <div class="col-md-4 col-md-offset-4">
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h3>
                                            <h:outputText value="#{takePollController.getItemFromListById(id).title}"/>
                                        </h3>
                                    </div>

                                    <div class="panel-body">
                                        <div class="radio">
                                            <h:selectOneRadio value="#{takePollController.selectedRadioOptions[id]}"
                                                              converter="omnifaces.SelectItemsConverter"
                                                              layout="pageDirection"
                                                              required="true"
                                                              requiredMessage="You suck!"
                                                              style="margin-left: 20px"
                                                              rendered="#{takePollController.getItemFromListById(id).type == 'ONE_OF_N' 
                                                                          || takePollController.getItemFromListById(id).type == 'YES_NO'}"> <!-- Aww yiss -->

                                                <f:selectItems value="#{takePollController.getSelectItemsByItemId(id)}"/>
                                            </h:selectOneRadio>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </ui:repeat>
                    <br/>
                    <div class="row">
                        <div class="col-md-4 col-md-offset-4">
                            <h:commandLink value="Submit" action="#{takePollController.submit}" styleClass="btn btn-primary btn-block"/>
                        </div>
                    </div>
                </h:form>
            </h:panelGroup>

            <!-- ======== Token invalid ======== -->
            <h:panelGroup id="tokenForm"
                          rendered="#{takePollController.token == null or !takePollController.token.valid}"
                          styleClass="container-fluid"
                          layout="block"
                          style="margin-top: 200px; margin-left: 0px; margin-right: 0px;">
                <div class="jumbotron">
                    <h2 class="text-danger">Invalid token <small>Please enter a valid token in the textfield below:</small>
                        <h:form styleClass="form-inline">
                            <div class="row">
                                <div class=""> <!-- col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 -->
                                    <div class="form-group">
                                        <h:inputText id="rawtoken"
                                                     value="#{takePollController.rawToken}"
                                                     styleClass="form-control"
                                                     required="true"
                                                     style="width: 290px">
                                        </h:inputText>
                                        <h:message for="rawtoken" style="color:red"/>
                                        <h:commandLink value="Take poll" styleClass="btn btn-default"/>
                                    </div>
                                </div>
                            </div>
                        </h:form>
                    </h2>
                </div>
            </h:panelGroup>
        </ui:define>
    </ui:composition>
</html>